# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # atau ganti dengan nama branch kamu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Build project (jika perlu)
      run: |
        mkdir dist
        echo "<h1>Hello from GitHub Actions!</h1>" > dist/index.html

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
